# Generated by Django 4.1.13 on 2025-12-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_published_post_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_published',
            new_name='published',
        ),
    ]
