# Generated by Django 4.1.13 on 2025-12-20 12:41

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_is_published_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=martor.models.MartorField(verbose_name='Содержание'),
        ),
    ]
