# Generated by Django 4.1.13 on 2025-12-13 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_en', models.CharField(max_length=100, verbose_name='Английское слово')),
                ('translation_ru', models.CharField(max_length=200, verbose_name='Перевод на русский')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_en', models.TextField(verbose_name='Текст на английском')),
                ('translation_ru', models.TextField(verbose_name='Перевод')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='vocabulary.word', verbose_name='Связанное слово')),
            ],
            options={
                'verbose_name': 'Текст (пример)',
                'verbose_name_plural': 'Тексты (примеры)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_en', models.TextField(verbose_name='Пример на английском')),
                ('translation_ru', models.TextField(verbose_name='Перевод')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='vocabulary.word', verbose_name='Связанное слово')),
            ],
            options={
                'verbose_name': 'Фраза',
                'verbose_name_plural': 'Фразы',
                'ordering': ['-created_at'],
            },
        ),
    ]
